/// @desc Draw the title screen.
var cam = VIEW_CAM;
var cam_left = camera_get_view_x(cam);
var cam_top = camera_get_view_y(cam);
var cam_right = cam_left + camera_get_view_width(cam);
var cam_bottom = cam_top + camera_get_view_height(cam);
var cam_xcentre = mean(cam_left, cam_right);
draw_set_colour(CPurple.MARDI_GRAS);
draw_set_valign(fa_bottom);
draw_set_halign(fa_center);
draw_set_font(fnt_tiny);
draw_text(cam_xcentre, cam_top + 40, "Katsaii & Mashmerlow");
draw_set_font(fnt_script);
draw_text(cam_xcentre, cam_top + 100, "Witch Whop");
draw_set_font(fnt_tiny);
draw_text(cam_xcentre, cam_top + 130, "High Score: " + string(global.highscore));
draw_set_font(fnt_complementary);
var option = lerp(cam_top, cam_bottom, optionThreshold);
draw_set_valign(fa_middle);
draw_set_halign(fa_center);
draw_text(cam_xcentre, option - 30, "Start");
draw_text(cam_xcentre, option + 30, "Exit");