/// @desc Draw the title screen.
var cam = VIEW_CAM;
var cam_left = camera_get_view_x(cam);
var cam_top = camera_get_view_y(cam);
var cam_right = cam_left + camera_get_view_width(cam);
var cam_bottom = cam_top + camera_get_view_height(cam);
var cam_xcentre = mean(cam_left, cam_right);
var blend = (1 + dsin(current_time * 0.1)) / 2;
var primary = merge_colour(CPurple.MARDI_GRAS, CYellow.REKINDLED, blend * 0.25);
draw_set_colour(primary);
draw_set_valign(fa_middle);
draw_set_halign(fa_center);
draw_set_font(fnt_tiny);
draw_text_wonky(cam_xcentre, cam_top + 30, "Katsaii & Mashmerlow");
draw_set_font(fnt_script);
draw_text_wonky(cam_xcentre, cam_top + 70, "Witch Whop");
draw_set_font(fnt_tiny);
draw_text_wonky(cam_xcentre, cam_bottom - 20, "High Score: " + string(global.highscore));
draw_set_font(fnt_complementary);
var option = lerp(cam_top, cam_bottom, optionThreshold);
draw_set_colour(selection == 0 ? CRed.FORREST_FIRE : primary);
draw_text_wonky(cam_xcentre, option - 30, "Start");
draw_set_colour(selection == 1 ? CRed.FORREST_FIRE : primary);
draw_text_wonky(cam_xcentre, option + 30, "Exit");