/// @desc Draw the title screen.
var cam = VIEW_CAM;
var cam_left = camera_get_view_x(cam);
var cam_top = camera_get_view_y(cam);
var cam_right = cam_left + camera_get_view_width(cam);
var cam_bottom = cam_top + camera_get_view_height(cam);
var cam_xcentre = mean(cam_left, cam_right);
var primary = COLOUR_BLEND;
var secondary = CRed.FORREST_FIRE;
draw_set_alpha(min(1, 4 * musicFade));
draw_set_colour(primary);
draw_set_valign(fa_middle);
draw_set_halign(fa_center);
draw_set_font(fnt_tiny);
draw_set_colour(selection == 2 ? secondary : primary);
draw_text_wonky(cam_xcentre - 60, cam_top + 20, "Katsaii");
draw_set_colour(primary);
draw_text_wonky(cam_xcentre - 20, cam_top + 20, "&");
draw_set_colour(selection == 3 ? secondary : primary);
draw_text_wonky(cam_xcentre + 50, cam_top + 20, "Mashmerlow");
draw_text_3d(cam_xcentre, cam_top + 105, "Protect the Island", 6, secondary, CYellow.REKINDLED);
draw_set_font(fnt_script);
draw_text_3d(cam_xcentre, cam_top + 80, "Witch Wanda", 12, make_color_rgb(86, 36, 92), make_color_rgb(203, 127, 212));
draw_set_font(fnt_tiny);
draw_set_colour(primary);
draw_text_wonky(cam_xcentre, cam_bottom - 20, "High Score: " + string(global.highscore));
draw_set_font(fnt_complementary);
var option = lerp(cam_top, cam_bottom, optionThreshold);
draw_set_colour(selection == 0 ? secondary : primary);
draw_text_wonky(cam_xcentre, option - 20, "Start");
draw_set_colour(selection == 1 ? secondary : primary);
draw_text_wonky(cam_xcentre, option + 20, "Exit");
draw_set_alpha(1.0);