/// @desc Initialise the gameloop.
gml_pragma("global", @'global.hp = 0; global.hpPool = 0;');
obj_title.visible = false;
hpMax = 20;
global.hp = hpMax;
global.hpPool = 0;
global.score = 0;
hpDrain = 0.015;
hpRecover = 0.1;
fadeIn = 0;
fadeInCounter = 0.005;
fadeOut = 0;
fadeOutCounter = 0.01;
gameRestart = false;
gameRestartTimer = 1;
gameRestartCounter = 0.01;
gameOver = false;
gameOverEmitter = audio_emitter_create();
crumbleEmitter = audio_emitter_create();
musicEmitter = audio_emitter_create();
musicFade = -0.25;
musicFadeCounter = 0.005;
audio_emitter_gain(gameOverEmitter, 0);
audio_emitter_gain(crumbleEmitter, 0);
audio_emitter_gain(musicEmitter, 0);
audio_play_sound_on(crumbleEmitter, snd_crumble, true, 100);
//audio_play_sound_on(musicEmitter, bgm_gameplay, true, 100);